In [2]:
print ("Hello World!")

Hello World!


In [5]:
def simple_math(a,b):
    sum = a+b
    if sum>2:
        return 2
    else:
        return sum
    
print (simple_math(1,2)) #na wykładzie podane bez nawiasów czyli dla Python 2.7, Python 3 wymaga dodania nawiasów w funkcji print

2


In [8]:
def my_fun():
    return 2
print (my_fun())

2


In [12]:
def Spanish_Inquisition(some_param):
    expect = False
    if some_param == 'Nobody':
        expect = True
    if expect == True:
        print (some_param + 'expects the Spanish inquisition')

In [13]:
my_list = [1,2,3,4,5,6,7,8]
my_list[1]

2

In [14]:
my_list = [1,2,3,4,5,6,7,8]
my_list[0]

1

In [16]:
my_list = [1,2,3,4,5,6,7,8]
my_list.append(9)
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
my_list = [1,2,3,4,5,6,7,8]
my_list.extend([10,11])
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 10, 11]


In [18]:
my_list = [1,2,3,4,5,6,7,8]
my_list.insert(0,0)
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [19]:
my_list = [1,2,3,4,5,6,7,8]
my_list.insert(6,22)
print(my_list)

[1, 2, 3, 4, 5, 6, 22, 7, 8]


In [20]:
my_list = [1,2,3,4,5,6,7,8]
my_list.insert(4,[2,3])
print(my_list)

[1, 2, 3, 4, [2, 3], 5, 6, 7, 8]


In [23]:
my_list = [1,2,3,4,5,6,7,8]
my_list.pop(4)

5

In [22]:
a=[1,2,3]
b=[1,2,3]
a+b

[1, 2, 3, 1, 2, 3]

In [26]:
my_list = [1,2,3]
my_tuple = (4,5,6)
#my_list + my_tuple #nie można dodac listy i tuple
tuple(my_list) + my_tuple

(1, 2, 3, 4, 5, 6)

In [27]:
txt = 'Ala'
int(txt) # nie można z tekstu zrobic liczby całkowitej

ValueError: invalid literal for int() with base 10: 'Ala'

In [28]:
txt = '1'
int(txt) # z liczby całkowitej mozna zrobic tekst

1

In [32]:
x = set([1,2])
x


{1, 2}

In [33]:
y = set('word')
y

{'d', 'o', 'r', 'w'}

In [42]:
d1 = dict()
d2 = ()
d3 = ("worker_name":"John","age":25)
d3["age"]

SyntaxError: invalid syntax (<ipython-input-42-8b78df8065bb>, line 3)

In [2]:
##02.06
PATH = ##define your path, in windows you need to add \\ in place of \
my_file=open(PATH,'r')
print(myfile)
print(myfile.read())

print(myfile.)

print("Cursor from start",myfile.read())
my_file.close()
print("Cursor from last",myfile.read()) ## will returen error due to it is trying to read closed file

my_file_2=open(PATH,'w')
print("some text", file = my_file_2) # write defined text to file

for i in range (5):
    print()("Some New Text" + str(i), file=my_file_2)
    my_file_2.close()
    my_file_2 = open(PATH, 'a')
    for i in ("foo","bar")*4):
        print(i,file=my_file_2)
        my_file_2.close()
    
    
    
    
##zapisywanie kodow elementu
pickle.load() ## odczytuje plik pickle i zapisuje go 
pickle.loads()

pickle.dump()
pickle.dumps()


##
import pickle
pickle.dump(a,file=open('object.pickle','wb'))
import os
print (os.getwd())

del(a)
new_object=pickle.loads(data=open('object.pickle',rb)).read()
print(new_object)

##json, jest wgrywany przez Pythona jako slownik
##csv, musimy wczytywac kazda linijke ktora jest rozpoznawana jako slownik



SyntaxError: invalid syntax (<ipython-input-2-3221158d0e53>, line 2)

In [4]:

##WIZUALIZACJA DANYCH
import matplotlib.pyplot as plt
import numpy as np

random=np.random.binomial(n=125,p=0.1, size =125)
plt.hist(random, bins =10)

print(random)
new_list = [1,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5]
plt.hist(new_list, bins =4)

plt.hist(random, bins =120, orientation = 'horizontal', color = 'red')


plt.xlabel('drank tea')
plt.ylabel('frequency')
plt.title('Tea drinking as normal distribution')
for i in range (2,20):
    plt.clf()
    plt.hist(random, bins =i, orientation = 'vertical', color = 'red')
    plt.show() #wywoluje wykres na konsoli oraz czysci poprzedni widok
plt.hist(random, bins =120, orientation = 'vertical', color = 'red')
plt.scatter([1,2,3],[4,6,7],color = 'red')
plt.scatter([8,9,10],[19,21,22], color - 'blue')


plt.close #zamyka wykresy i usuwa je z pamieci




ImportError: No module named 'matplotlib'

In [6]:
#SEABORN
import seaborn as sns
#BOKEH
#geoplotlib


NameError: name 'plt' is not defined

In [7]:
#parsownaie stron internetowych

import ulrlib
my_pjatk=urllib.request.urlopen('https://www.pja.edu.pl') #ctrl+u podglad strony www
print(my_pjatk.info())
print(my_pjatk.read())



#SOUP
from bs4 import BeautifulSoup
soup= BeautifulSoup(my_pjatk.read(),'thml.parser')
print(soup.find_all('p'))

print(paragraphs[0].get_text())

for paragraph in paragraphs:
    print(paragraph.attrs)
    print(paragraph.get_text())
    print(paragraphs)

paragraphs = soup.find_all('a)
for paragraph in paragraphs:
    a_dict = paragraph.attrs
    if a_dict.__contains__('href'):
        print(a_dict['href'])

SyntaxError: EOL while scanning string literal (<ipython-input-7-c105fe69d4d7>, line 22)

In [12]:
#NumPy, SciPy
import numpy as np
df=np.array([('A',175),('B',182),('0',185)],dtype = [('Blood_type','S10'),('Height','>f4')])
print(df['Blood_type'])


[b'A' b'B' b'0']


In [20]:
import numpy as np
matrix  = np.array([[1,2,3],[-1,3,4],[0,5,6]],dtype='int8')
print(np.amin(matrix, axis =0),'\n', matrix)
print(np.amin(matrix, axis =1),'\n', matrix)
print(np.amax(matrix, axis =0),'\n', matrix)
print(np.amax(matrix, axis =1),'\n', matrix)




[-1  2  3] 
 [[ 1  2  3]
 [-1  3  4]
 [ 0  5  6]]
[ 1 -1  0] 
 [[ 1  2  3]
 [-1  3  4]
 [ 0  5  6]]
[1 5 6] 
 [[ 1  2  3]
 [-1  3  4]
 [ 0  5  6]]
[3 4 6] 
 [[ 1  2  3]
 [-1  3  4]
 [ 0  5  6]]


In [32]:
import numpy as np
import matplotlib.pylot as plt
normal = np.random.normal(loc=10,scale=5,size = 250)
plt.hist(normal, bins =20)
plt.show()
poisson=np.random.poisson(lam =3, size = 250)

plt.show()
binomial = np.random.binomial(n=10,p=0.5,size= 250)
plt.hist(binomial, bins = 20)
plt.show

ImportError: No module named 'matplotlib'

In [33]:
import numpy as np
import matplotlib.pylot as plt
from scipy.stats import norm
normal = np.random.normal(loc=10,scale=5,size = 250)
print(norm.pdf(normal))

ImportError: No module named 'matplotlib'

In [9]:
import numpy as np
x = np.array([[1,2],[3,4],[10,1]])
y = np.array([[2,4],[4,5],[6,7]])
print(np.transpose(x))
print()
print(x*y) #mnozenie 1to1 (arytmetyczne), potrzeba zmienić na liczba kolumn musi być równa liczbie wierszy, można zrobić to przez transponowanie macierzy
print()
print(np.dot(x,np.transpose(y)))
print()

[[ 1  3 10]
 [ 2  4  1]]

[[ 2  8]
 [12 20]
 [60  7]]

[[10 14 20]
 [22 32 46]
 [24 45 67]]

<built-in function dot>


In [10]:
help(np.dot)

Help on built-in function dot in module numpy.core.multiarray:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Se

In [11]:
%matplotlib inline
import numpy as np
import matplotlib.pylot as plt

x = np.array([[1,2],[3,4],[10,1]])
y = np.array([[2,4],[4,5],[6,7]])

x_norm=np.random.normal(loc =10, scale = 2, size=20)
y_norm=np.random.normal(loc =10, scale = 3, size=20)

plt.scatter(x_norm, y_norm)
print('covariance',np.cov(x_norm,y_norm))
print('corelation',np.corrcoef(x_norm, y_norm))

ImportError: No module named 'matplotlib'

In [1]:
import numpy as np
import matplotlib.pylot as plt
import csv

x=[]
for x in range(10):
    x.append(np.random.randint(10))
print(x)    
y=[1,2,3,4,2,3,4,2,3,5]
z=[10,21,32,19,35,12,26,36,15,45]


predicatles=np.array([y,x])
print(predictables.shape)
print(predicatles)
plt.scatter(y,z)

my_model=np.linalg.lstsq(np.transpose(predictables))

ModuleNotFoundError: No module named 'matplotlib.pylot'

In [3]:
from scipy import spatial
y=[1,2,3,4,2,3,4,2,3,5]
z=[10,21,32,19,35,12,26,36,15,45]
print(spatial.distance.cosine(y,z))

0.09123084291442418


In [4]:
#text mining, biblioteka NLTK - natural language toolkit
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True